// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID        int32
	Title     string
	Content   string
	CreatedAt pgtype.Timestamptz
}

type NoteImage struct {
	ID        int32
	NoteID    pgtype.Int4
	ImageUrl  string
	Caption   pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type NoteTag struct {
	NoteID int32
	TagID  int32
}

type Tag struct {
	ID  int32
	Tag string
}
