// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tags.sql

package repository

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags(tag) VALUES ($1) RETURNING id, tag
`

func (q *Queries) CreateTag(ctx context.Context, tag string) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, tag)
	var i Tag
	err := row.Scan(&i.ID, &i.Tag)
	return i, err
}
